### PR TITLE
Change to the new api that more like to the common api.

### PR DESCRIPTION
**Pull request by djx314**
Affected by the api from ubw, I have change this project's api to the new that more likely to the common slick api.

### CODE REVIEW

**Comment by djx314** [comment]
@jilen Any suggests with this change? Is it better or worse?

``` scala
val updateQ =
  for {
    small <- smallTq.filter(_.id === 2333L).hf
  } yield {
    List(
      small.a1.gen to 2333 need ("github" == "github"),
      small.a2.gen to Some(2333) need ("scala" == "china"),
      small.a3.gen to "wang"
    )
  }

val finalQ = updateQ.update.transactionally
```

**Comment by djx314** [comment]
@jilen 
Now the api has changed. No longer need the .gen. It seems like this:

``` scala
val updateQ =
  for {
    small <- smallTq.hf if small.id === 2333L
  } yield {
    List(
      small.a1 to 2333 need ("github" == "github"),
      small.a2 to Some(2333) need ("scala" == "china"),
      small.a3 to "wang"
    )
  }

val finalQ = updateQ.update.transactionally
```

when use

``` scala
updateQ.update
```

that calls slick's update method.
when use

``` scala
updateQ.insert
```

that calls slick's += method

**Comment by jilen** [comment]
I think we can use `setTo` instead of `to` , `when` instead of `need`

**Comment by djx314** [comment]
LGTM

**Pull request merged**
